//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface USContentUnitViewControllerCache : NSObject
{
    NSMutableDictionary *_actionMapIDToControllerMap;
    id <USContentUnitViewControllerCacheDelegate> _delegate;
}

@property(nonatomic) __weak id <USContentUnitViewControllerCacheDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSMutableDictionary *actionMapIDToControllerMap; // @synthesize actionMapIDToControllerMap=_actionMapIDToControllerMap;
- (id)anyControllerForScope:(id)arg1;
- (id)controllerForActionMapID:(id)arg1;
- (void)removeController:(id)arg1;
- (void)addController:(id)arg1;

@end

