//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLConnectionDataDelegate.h"

@class NSMutableDictionary, NSString;

@interface USURLLoader : NSObject <NSURLConnectionDataDelegate>
{
    NSMutableDictionary *_connections;
}

@property(retain, nonatomic) NSMutableDictionary *connections; // @synthesize connections=_connections;
- (void).cxx_destruct;
- (void)openURL:(id)arg1;
- (void)invalidateConnection:(id)arg1;
- (_Bool)isRequestWithStandardURLScheme:(id)arg1;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)loadURL:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

